[project]
name = "crptb2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ccxt>=4.4.25",
    "pandas>=2.2.3",
    "ruff>=0.7.1",
]
