# ログ設定
logging:
  level: DEBUG
  file: trading_bot.log

# 取引所設定
exchange:
  name: bybit
  api_key: ""
  api_secret: ""
  symbol: BTCUSDT
  position_size: 0.001
  leverage: 10
  buy_leverage: 10
  sell_leverage: 10
  margin_type: cross
  timeframe: 15m
  max_position: 0.001
  retry_count: 5
  retry_interval: 10
  testnet: false
  dry_run: true  # エントリー条件を満たしても実際には注文をしないモード
  simulation_initial_balance: 500  # シミュレーション用初期残高（USDT）
  fee_rate: 0.0550  # Bybitの無期限・先物取引テイカー手数料(VIP0)

discord:
  webhook_url: ""
  enabled: true
  mention_user_id: "278736529084514314" # teihenn981
