# ログ設定
logging:
  level: DEBUG
  file: trading_bot.log

# 取引所設定
exchange:
  name: bybit
  api_key: ""
  api_secret: ""
  symbol: BTCUSDT
  position_size: 0.001
  leverage: 10
  buy_leverage: 10
  sell_leverage: 10
  margin_type: cross
  timeframe: 15m
  max_position: 0.001
  retry_count: 5
  retry_interval: 10
  testnet: true

discord:
  webhook_url: ""
  enabled: true
